-- =====================================================================
-- Catalogue reset: remove every product, variant, order and payment,
-- then load 3 products (RAL Colour-Coated Sheets, Roofing Sheets, Stone-Coated Roof Tiles)
-- with one variant per colour and up to 10 gallery photos each.
--
-- Generated by catalog-upload/build_catalog.py — edit that, not this.
--
-- BEFORE RUNNING IN PRODUCTION
--   1. Back up the database (mysqldump/mariadb-dump). This is destructive.
--   2. Apply drizzle/0014_product_images_color.sql (adds
--      product_images.color_id, which this script fills in).
--   3. Upload every file in catalog-upload/files/ into the production
--      FILES_DIR (flat, same names). The SQL only stores the names.
--
-- KEPT: customers, user accounts, staff, warehouses, raw materials,
--   purchase orders (finished-goods lines pointing at old variants are
--   removed), promo codes, blog, site settings/images, FAQ, testimonials,
--   and the colour/width/thickness/length/category lookup tables (missing
--   entries the new products need are added). Categories left with no
--   products are hidden (is_active = FALSE), not deleted.
--
-- Runs in one transaction: if any statement fails, nothing is changed.
-- =====================================================================

START TRANSACTION;

-- 1. Orders and everything hanging off them ---------------------------
DELETE FROM quote_replies;
DELETE FROM quote_requests;
DELETE FROM payment_links;
DELETE FROM price_offers;
DELETE FROM order_adjustments;
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM product_adjustments;
DELETE FROM transactions;

-- 2. Stock and production records tied to the old variants -----------
DELETE FROM production_batches;
DELETE FROM purchase_order_items WHERE variant_id IS NOT NULL;
DELETE FROM stock_levels;

-- 3. The catalogue itself --------------------------------------------
DELETE FROM variant_prices;
DELETE FROM product_variants;
DELETE FROM product_images;
DELETE FROM product_tags;
DELETE FROM categories_products;
DELETE FROM discounts;
DELETE FROM damaged_products;
DELETE FROM products;

-- 4. Lookups the new products need (added only if missing) ------------
INSERT INTO product_categories (name, description)
SELECT * FROM (
	SELECT 'RAL colours' AS name, 'Colour-coated sheets in named RAL shades' AS description UNION ALL
	SELECT 'Roofing sheets', 'Trapezoidal, corrugated and printed roofing sheets' UNION ALL
	SELECT 'Roofing tiles', 'Roofing tiles'
) AS c
WHERE NOT EXISTS (SELECT 1 FROM product_categories pc WHERE pc.name = c.name);
SET @cat_ral = (SELECT id FROM product_categories WHERE name = 'RAL colours');
SET @cat_sheet = (SELECT id FROM product_categories WHERE name = 'Roofing sheets');
SET @cat_tile = (SELECT id FROM product_categories WHERE name = 'Roofing tiles');

INSERT INTO colors (name, code, hex_value)
SELECT * FROM (
	SELECT 'Flame Red' AS name, 'RAL 3000' AS code, '#A72920' AS hex_value UNION ALL
	SELECT 'Traffic Green', 'RAL 6024', '#308446' UNION ALL
	SELECT 'Traffic Blue', 'RAL 5017', '#0E518D' UNION ALL
	SELECT 'Cream', 'RAL 9001', '#E9E0D2' UNION ALL
	SELECT 'Signal Red', 'RAL 3001', '#A52019' UNION ALL
	SELECT 'Moss Green', 'RAL 6005', '#2F4538' UNION ALL
	SELECT 'Grass Print', 'Printed', '#3F9A3C' UNION ALL
	SELECT 'Terracotta', 'RAL 8004', '#9C4E2E' UNION ALL
	SELECT 'Jet Black', 'RAL 9005', '#0A0A0A'
) AS c
WHERE NOT EXISTS (SELECT 1 FROM colors x WHERE x.name = c.name);
SET @color_flame_red = (SELECT id FROM colors WHERE name = 'Flame Red');
SET @color_traffic_green = (SELECT id FROM colors WHERE name = 'Traffic Green');
SET @color_traffic_blue = (SELECT id FROM colors WHERE name = 'Traffic Blue');
SET @color_cream = (SELECT id FROM colors WHERE name = 'Cream');
SET @color_signal_red = (SELECT id FROM colors WHERE name = 'Signal Red');
SET @color_moss_green = (SELECT id FROM colors WHERE name = 'Moss Green');
SET @color_grass = (SELECT id FROM colors WHERE name = 'Grass Print');
SET @color_terracotta = (SELECT id FROM colors WHERE name = 'Terracotta');
SET @color_black = (SELECT id FROM colors WHERE name = 'Jet Black');

INSERT INTO widths (value, unit, label)
SELECT * FROM (SELECT 913.00 AS value, 'mm' AS unit, '3 Feet (914mm)' AS label UNION ALL
	SELECT 1219.00, 'mm', '4 Feet Standard Coil (1219mm)') AS w
WHERE NOT EXISTS (SELECT 1 FROM widths x WHERE x.value = w.value AND x.unit = w.unit);
INSERT INTO thicknesses (value, unit, label)
SELECT 0.425, 'mm', '0.425mm High-Tensile Cladding' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM thicknesses WHERE value = 0.425 AND unit = 'mm');
INSERT INTO lengths (value, unit, label)
SELECT * FROM (SELECT 2.00 AS value, 'm' AS unit, 'Standard 2.0m Sheet' AS label UNION ALL
	SELECT 3.00, 'm', 'Standard 3.0m Sheet') AS l
WHERE NOT EXISTS (SELECT 1 FROM lengths x WHERE x.value = l.value AND x.unit = l.unit);
SET @w_913 = (SELECT id FROM widths WHERE value = 913.00 AND unit = 'mm');
SET @w_1219 = (SELECT id FROM widths WHERE value = 1219.00 AND unit = 'mm');
SET @t_0425 = (SELECT id FROM thicknesses WHERE value = 0.425 AND unit = 'mm');
SET @l_2 = (SELECT id FROM lengths WHERE value = 2.00 AND unit = 'm');
SET @l_3 = (SELECT id FROM lengths WHERE value = 3.00 AND unit = 'm');

-- 5. Products, colour variants and galleries -------------------------
-- RAL Colour-Coated Sheets ----------------------------------------------
INSERT INTO products (name, slug, brand, category_id, featured_image, description, overview,
	quantity, reorder_level, sold_by, thickness, width, max_length, max_length_unit,
	is_length_customizable, min_length, length_step, coating_type, color_options, size_range,
	finish, performance_features, advantages, applications, is_featured_on_home)
VALUES ('RAL Colour-Coated Sheets', 'ral-colour-coated-sheets', 'DANA', @cat_ral, 'catalog-ral-3000.webp', 'Pre-painted galvanized sheets coated to a named RAL shade, matched batch to batch.', 'Colour-coated PPGI sheets in exact RAL shades — pick the code, we coat to it, and every repeat order matches.', 0, 10, 'quantity', '0.23–0.80 mm', '914 / 1000 / 1219 mm', 12.00, 'm', TRUE, 1.00, 0.50, 'PPGI', '#A72920, #308446, #0E518D, #E9E0D2', 'Standard Lengths', 'Pre-painted · Glossy', 'Weather-resistant coating with high UV degradation protection.', 'Exact RAL shade on every sheet, so extensions and repeat orders match the original roof.', 'Roofing · cladding · facades', FALSE);
SET @ral = LAST_INSERT_ID();
INSERT INTO categories_products (category_id, product_id) VALUES (@cat_ral, @ral);

INSERT INTO product_variants (product_id, color_id, width_id, thickness_id, length_id, sku, price, quantity, reorder_level, image_url) VALUES
	(@ral, @color_flame_red, @w_913, @t_0425, @l_3, 'RAL-3000', 1250.00, 150, 20, 'catalog-ral-3000.webp'),
	(@ral, @color_traffic_green, @w_913, @t_0425, @l_3, 'RAL-6024', 1250.00, 150, 20, 'catalog-ral-6024.webp'),
	(@ral, @color_traffic_blue, @w_913, @t_0425, @l_3, 'RAL-5017', 1250.00, 150, 20, 'catalog-ral-5017.webp'),
	(@ral, @color_cream, @w_913, @t_0425, @l_3, 'RAL-9001', 1250.00, 150, 20, 'catalog-ral-9001.webp');

INSERT INTO product_images (product_id, image_url, color_id) VALUES
	(@ral, 'catalog-ral-3000.webp', @color_flame_red),
	(@ral, 'catalog-ral-6024.webp', @color_traffic_green),
	(@ral, 'catalog-ral-5017.webp', @color_traffic_blue),
	(@ral, 'catalog-ral-9001.webp', @color_cream),
	(@ral, 'catalog-roof-red-02.webp', @color_flame_red),
	(@ral, 'catalog-roof-green-02.webp', @color_traffic_green),
	(@ral, 'catalog-roof-blue-02.webp', @color_traffic_blue),
	(@ral, 'catalog-fence-white-01.webp', @color_cream),
	(@ral, 'catalog-fence-red-01.webp', @color_flame_red),
	(@ral, 'catalog-fence-blue-02.webp', @color_traffic_blue);

-- Roofing Sheets --------------------------------------------------------
INSERT INTO products (name, slug, brand, category_id, featured_image, description, overview,
	quantity, reorder_level, sold_by, thickness, width, max_length, max_length_unit,
	is_length_customizable, min_length, length_step, coating_type, color_options, size_range,
	finish, performance_features, advantages, applications, is_featured_on_home)
VALUES ('Roofing Sheets', 'roofing-sheets', 'DANA', @cat_sheet, 'catalog-sheet-red.webp', 'Trapezoidal and corrugated colour-coated roofing sheets, including printed finishes.', 'Profiled PPGI sheets for roofs, walls and fencing — in solid colours or printed patterns.', 0, 10, 'quantity', '0.23–0.80 mm', '914 / 1000 / 1219 mm', 12.00, 'm', TRUE, 1.00, 0.50, 'PPGI', '#A52019, #0E518D, #2F4538, #3F9A3C', 'Trapezoidal · Corrugated · Step profiles', 'Pre-painted · Printed', 'Profiled ribs for stiffness over wide purlin spacing; weather-resistant coating.', 'Light, quick to install and available in long single runs.', 'Roofing · wall cladding · fencing', FALSE);
SET @sheet = LAST_INSERT_ID();
INSERT INTO categories_products (category_id, product_id) VALUES (@cat_sheet, @sheet);

INSERT INTO product_variants (product_id, color_id, width_id, thickness_id, length_id, sku, price, quantity, reorder_level, image_url) VALUES
	(@sheet, @color_signal_red, @w_913, @t_0425, @l_3, 'SHEET-RED', 1250.00, 150, 20, 'catalog-sheet-red.webp'),
	(@sheet, @color_traffic_blue, @w_913, @t_0425, @l_3, 'SHEET-BLU', 1250.00, 150, 20, 'catalog-sheet-blue.webp'),
	(@sheet, @color_moss_green, @w_913, @t_0425, @l_3, 'SHEET-GRN', 1250.00, 150, 20, 'catalog-sheet-green.webp'),
	(@sheet, @color_grass, @w_913, @t_0425, @l_3, 'SHEET-GRASS', 1250.00, 150, 20, 'catalog-sheet-grass.webp');

INSERT INTO product_images (product_id, image_url, color_id) VALUES
	(@sheet, 'catalog-sheet-red.webp', @color_signal_red),
	(@sheet, 'catalog-sheet-blue.webp', @color_traffic_blue),
	(@sheet, 'catalog-sheet-green.webp', @color_moss_green),
	(@sheet, 'catalog-sheet-grass.webp', @color_grass),
	(@sheet, 'catalog-sheet-red-step.webp', @color_signal_red),
	(@sheet, 'catalog-sheet-factory.webp', NULL),
	(@sheet, 'catalog-fence-blue-02.webp', @color_traffic_blue),
	(@sheet, 'catalog-fence-red-06.webp', @color_signal_red),
	(@sheet, 'catalog-roof-green-03.webp', @color_moss_green),
	(@sheet, 'catalog-roof-blue-03.webp', @color_traffic_blue);

-- Stone-Coated Roof Tiles -----------------------------------------------
INSERT INTO products (name, slug, brand, category_id, featured_image, description, overview,
	quantity, reorder_level, sold_by, thickness, width, max_length, max_length_unit,
	is_length_customizable, min_length, length_step, coating_type, color_options, size_range,
	finish, performance_features, advantages, applications, is_featured_on_home)
VALUES ('Stone-Coated Roof Tiles', 'stone-coated-roof-tiles', 'DANA', @cat_tile, 'catalog-tile-terracotta.webp', 'Steel roof tiles with a stone-chip finish, with matching ridge caps.', 'Stone-coated steel tiles give the look of clay at a fraction of the weight; matching ridge caps finish the roof line.', 0, 10, 'quantity', '0.30–0.50 mm', '1080 mm cover', 6.00, 'm', TRUE, 1.00, 0.50, 'Stone-coated GI', '#9C4E2E, #0A0A0A', 'Tile panels · Ridge caps', 'Stone-chip texture', 'Stone granules bonded over coated steel resist fading and hail, and quieten rain.', 'Clay-tile look without the weight; ridge caps come in the same colours.', 'Residential · villas · commercial roofs', FALSE);
SET @tile = LAST_INSERT_ID();
INSERT INTO categories_products (category_id, product_id) VALUES (@cat_tile, @tile);

INSERT INTO product_variants (product_id, color_id, width_id, thickness_id, length_id, sku, price, quantity, reorder_level, image_url) VALUES
	(@tile, @color_terracotta, @w_1219, @t_0425, @l_2, 'TILE-TER', 22.00, 900, 80, 'catalog-tile-terracotta.webp'),
	(@tile, @color_black, @w_1219, @t_0425, @l_2, 'TILE-BLK', 22.00, 900, 80, 'catalog-tile-black.webp');

INSERT INTO product_images (product_id, image_url, color_id) VALUES
	(@tile, 'catalog-tile-terracotta.webp', @color_terracotta),
	(@tile, 'catalog-tile-black.webp', @color_black),
	(@tile, 'catalog-ridge-cap-brown.webp', @color_terracotta),
	(@tile, 'catalog-ridge-cap-black.webp', @color_black),
	(@tile, 'catalog-roof-terracotta-02.webp', @color_terracotta),
	(@tile, 'catalog-roof-black-01.webp', @color_black),
	(@tile, 'catalog-roof-terracotta-05.webp', @color_terracotta),
	(@tile, 'catalog-roof-black-06.webp', @color_black),
	(@tile, 'catalog-roof-terracotta-01.webp', @color_terracotta),
	(@tile, 'catalog-roof-black-03.webp', @color_black);

-- Stock lives in stock_levels (see src/lib/server/stock.ts); the
-- quantity columns are totals synced from it. Put each variant's opening
-- stock in the default warehouse, creating one the way migration 0012
-- does if none is marked default yet.
INSERT INTO warehouses (name, is_default, is_active)
SELECT 'Main Warehouse', TRUE, TRUE FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM warehouses WHERE is_default = TRUE);
SET @warehouse = (SELECT MIN(id) FROM warehouses WHERE is_default = TRUE);
INSERT INTO stock_levels (variant_id, warehouse_id, quantity)
SELECT id, @warehouse, quantity FROM product_variants WHERE product_id IN (@ral, @sheet, @tile);
UPDATE products p SET quantity = (SELECT COALESCE(SUM(v.quantity), 0) FROM product_variants v WHERE v.product_id = p.id)
WHERE p.id IN (@ral, @sheet, @tile);

-- Hide categories that no product uses any more, so the shop filter only
-- lists ones with something in them. Reversible: set is_active back.
UPDATE product_categories SET is_active = (id IN (SELECT category_id FROM products));

-- One per-piece rate per variant, matching its retail price (same
-- convention as the earlier seeds).
INSERT INTO variant_prices (variant_id, basis, price, price_includes_vat)
SELECT id, 'quantity', price, FALSE FROM product_variants WHERE product_id IN (@ral, @sheet, @tile);

COMMIT;
